version: '3.4'

services:
  ntp_server:
    image: devafatek/ntpserver
    labels:
      - "author=devafatek"
    container_name: ntp_server
    restart: always
    ports:
      - 123:123/udp
    cap_add:
      - SYS_NICE
      - SYS_RESOURCE
      - SYS_TIME
    environment:
      NTP_SERVERS: time.cloudflare.com
      TZ: Europe/Istanbul
